# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('addtocart_date_time', models.DateTimeField()),
                ('order_status', models.CharField(default=b'pending in cart', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemtype', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subject', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('department', models.CharField(choices=[(b'COMPS', b'COMPUTERS'), (b'IT', b'INFORMATION_TECHNOLOGY'), (b'ELEX', b'ELECTRONICS'), (b'EXTC', b'ELECTRONICS_TELECOMM'), (b'MECH', b'MECHANICAL'), (b'PROD', b'PRODUCTION'), (b'BIO', b'BIOMEDICAL')], max_length=6, null=True)),
                ('year', models.CharField(choices=[(b'FE', b'FIRST_YEAR'), (b'SE', b'SECOND_YEAR'), (b'TE', b'THIRD_YEAR'), (b'BE', b'FOURTH_YEAR')], max_length=2)),
                ('image', models.ImageField(blank=True, upload_to=b'items/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_no', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('department', models.CharField(choices=[(b'COMPS', b'COMPUTERS'), (b'IT', b'INFORMATION_TECHNOLOGY'), (b'ELEX', b'ELECTRONICS'), (b'EXTC', b'ELECTRONICS_TELECOMM'), (b'MECH', b'MECHANICAL'), (b'PROD', b'PRODUCTION'), (b'BIO', b'BIOMEDICAL')], max_length=6, null=True)),
                ('address', models.CharField(max_length=100)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SiteUser'),
        ),
    ]
